<?php

namespace Migrartabela\Payloads;
class PlanoPayload
{
    private const DEFAULTS = [
       
        'IdFilial'                         => 1,
        'Data'                             => '',
        'Usuario'                          => 1,
        'plano_carteirinha_id'             => null,
        'IdTermo'                          => null,
        'plano_quitado'                    => 0,
        'Descricao'                        => null,
        'LimiteDependentes'                => 10,
        'id_adicional_dependente'          => null,
        'PeriodicidadeParcelas'            => 1,
        'Urna'                             => '',
        'Adesao'                           => '0.00',
        'adesao_valor_fixo'                => 1,
        'AdesaoCartao'                     => null,
        'TipoCobranca'                     => 0,
        'ValidadeCartao'                   => 0,
        'Atualizacao'                      => null,
        'SuspenderContrato'                => 3,
        'SuspenderContratoTipo'            => 1,
        'QuitacaoContrato'                 => 0,
        'QuitacaoTipo'                     => null,
        'aviso_quitacao_default'           => 'Cliente com plano quitado, permanecendo isento do pagamento das mensalidades até que haja a necessidade de utilização dos serviços, quando então o contrato será reativado.',
        'observacao_quitacao'              => null,
        'CarenciaContrato'                 => 90,
        'CarenciaContratoPag'              => 0,
        'CarenciaPagamento'                => 90,
        'CarenciaNegociacao'               => 90,
        'CarenciaReativacao'               => 90,
        'CarenciaPlano'                    => 90,
        'CarenciaAdereco'                  => 90,
        'CarenciaDependente'               => 90,
        'VigenciaContrato'                 => 0,
        'MesLimite'                        => 12,
        'Reajuste'                         => '0.00',
        'TipoDesconto'                     => 0,
        'ValorDesconto'                    => 0,
        'CondicionalDesconto'              => 0,
        'StatusSite'                       => 0,
        'permite_alteracoes_dependentes'   => 1,
        'limite_alteracoes_dependentes'    => 3,
        'count_obitos_pessoa_titularidade' => 1,
        'limite_parcelas_visiveis_no_app'  => 0,
        'IdStatus'                         => 1,
        'IdPlanoMigracao'                  => null,
        'DataReajuste'                     => null,
        'DataFinalEmissao'                 => null,
    ];
    public static function criar(array $dados): array
    {

    //Inverti a ordem dos arrays para garantir que os valores de $dados prevaleçam sobre os defaults, caso existam.
        $dados = array_replace($dados, self::DEFAULTS,);

        return [
           // 'plano_carteirinha_id'            => $dados['plano_carteirinha_id'],
            'IdFilial'                        => $dados['IdFilial'],
            'IdTermo'                         => $dados['IdTermo'],
            'plano_quitado'                   => $dados['plano_quitado'],
            'Plano'                           => $dados['Plano'],
            'Descricao'                       => $dados['Descricao'],
            'LimiteDependentes'               => $dados['LimiteDependentes'],
            'id_adicional_dependente'         => $dados['id_adicional_dependente'],
            'PeriodicidadeParcelas'           => $dados['PeriodicidadeParcelas'],
            'Urna'                            => $dados['Urna'],
            'Valor'                           => $dados['Valor'],
            'Adesao'                          => $dados['Adesao'],
            'adesao_valor_fixo'               => $dados['adesao_valor_fixo'],
            'AdesaoCartao'                    => $dados['AdesaoCartao'],
            'TipoCobranca'                    => $dados['TipoCobranca'],
            'ValidadeCartao'                  => $dados['ValidadeCartao'],
            'Data'                            => $dados['Data'],
            'Atualizacao'                     => $dados['Atualizacao'],
            'SuspenderContrato'               => $dados['SuspenderContrato'],
            'SuspenderContratoTipo'           => $dados['SuspenderContratoTipo'],
            'QuitacaoContrato'                => $dados['QuitacaoContrato'],
            'QuitacaoTipo'                    => $dados['QuitacaoTipo'],
            'aviso_quitacao_default'          => $dados['aviso_quitacao_default'],
            'observacao_quitacao'             => $dados['observacao_quitacao'],
            'CarenciaContrato'                => $dados['CarenciaContrato'],
            'CarenciaContratoPag'             => $dados['CarenciaContratoPag'],
            'CarenciaPagamento'               => $dados['CarenciaPagamento'],
            'CarenciaNegociacao'              => $dados['CarenciaNegociacao'],
            'CarenciaReativacao'              => $dados['CarenciaReativacao'],
            'CarenciaPlano'                   => $dados['CarenciaPlano'],
            'CarenciaAdereco'                 => $dados['CarenciaAdereco'],
            'CarenciaDependente'              => $dados['CarenciaDependente'],
            'VigenciaContrato'                => $dados['VigenciaContrato'],
            'MesLimite'                       => $dados['MesLimite'],
            'DataReajuste'                    => $dados['DataReajuste'] ?? $dados['Data'],
            'DataFinalEmissao'                => $dados['DataFinalEmissao'] ?? $dados['Data'],
            'Reajuste'                        => $dados['Reajuste'],
            'TipoDesconto'                    => $dados['TipoDesconto'],
            'ValorDesconto'                   => $dados['ValorDesconto'],
            'CondicionalDesconto'             => $dados['CondicionalDesconto'],
            'StatusSite'                      => $dados['StatusSite'],
            'permite_alteracoes_dependentes'  => $dados['permite_alteracoes_dependentes'],
            'limite_alteracoes_dependentes'   => $dados['limite_alteracoes_dependentes'],
            'count_obitos_pessoa_titularidade'=> $dados['count_obitos_pessoa_titularidade'],
           // 'limite_parcelas_visiveis_no_app' => $dados['limite_parcelas_visiveis_no_app'],
            'Usuario'                         => $dados['Usuario'],
            'IdStatus'                        => $dados['IdStatus'],
            'IdPlanoMigracao'                 => $dados['IdPlanoMigracao'],
            'externo_id'                      => $dados['externo_id'],
        ];
    }
}
